name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy flake8

    - name: Lint
      run: make lint

    - name: Build
      run: make build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pytest bandit

      - name: Test
        run: make test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: junit/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy stage
        run: echo "Deploying the project..."
