name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: Build stage
      #   run: echo "Building the project..."
        # Здесь могут быть команды для сборки проекта, например, python setup.py build
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies & build
      run: |
        python -m pip install --upgrade pip
        make build
        # pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Lint with flake8
    #   run: |
    #     # остановить сборку, если есть ошибки стиля
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # выход с кодом 0, если нет ошибок стиля
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test stage
        run: |
          echo "Running tests..."
          make test
        # Здесь могут быть команды для тестирования проекта, например, pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy stage
        run: echo "Deploying the project..."
